insert into "csp_app_states" (pk_state_code,zone,state_name) values(1,'EAST','ARUNACHAL PRADESH');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(11,'EAST','ASSAM');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(2,'EAST','BIHAR');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(3,'EAST','CHHATTISGARH');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(4,'EAST','JHARKHAND');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(5,'EAST','MANIPUR');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(6,'EAST','MEGHALAYA');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(7,'EAST','MIZORAM');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(8,'EAST','NAGALAND');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(9,'EAST','ODISHA');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(10,'EAST','SIKKIM');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(12,'EAST','TRIPURA');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(13,'EAST','WEST BENGAL');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(14,'NORTH','CHANDIGARH');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(15,'NORTH','HARYANA');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(16,'NORTH','HIMACHAL PRADESH');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(17,'NORTH','JAMMU & KASHMIR');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(18,'NORTH','NEW DELHI');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(19,'NORTH','PUNJAB');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(20,'NORTH','RAJASTHAN');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(21,'NORTH','UTTAR PRADESH');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(22,'NORTH','UTTARAKHAND');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(23,'SOUTH','ANDHRA PRADESH');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(24,'SOUTH','KARNATAKA');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(25,'SOUTH','KERALA');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(26,'SOUTH','PUDUCHERRY');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(27,'SOUTH','TAMIL NADU');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(28,'SOUTH','TELANGANA');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(29,'WEST','GOA');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(30,'WEST','GUJARAT');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(32,'WEST','MADHYA PRADESH');
insert into "csp_app_states" (pk_state_code,zone,state_name) values(31,'WEST','MAHARASHTRA');

delete from "csp_app_gross_salary_history";
delete from "csp_app_candidate_document";
delete from "csp_app_salary_structure";
delete from "csp_app_master_candidate";
delete from "csp_app_dummy_candidate";
delete from "csp_app_master_location";
delete from "csp_app_master_city";
delete from "csp_app_master_state";
delete from "csp_app_master_region";
delete from "csp_app_master_designation";
delete from "csp_app_master_sub_team";
delete from "csp_app_master_team";
delete from "csp_app_master_function";
delete from "csp_app_master_department";
delete from "csp_app_master_vendor";
delete from "csp_app_master_entity";
delete from "csp_app_master_minimum_wages";
delete from "csp_app_csp_candidate_code";
delete from "csp_app_dummy_candidate_code";
insert into "csp_app_csp_candidate_code" values(0, 'C000000000');
insert into "csp_app_dummy_candidate_code" values(0, 'D000000000');
delete from "csp_app_group_ids";
insert into "csp_app_group_ids" values(0);
delete from "auth_user" where not id = 1 and not id = 23 and not id = 24;
delete from "auth_user_groups" where not user_id = 1 and not user_id = 23 and not user_id = 24;




-- Andaman & Nicobar
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Alipur', '101','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Andaman Island', '102','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Anderson Island', '103','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Arainj-Laka-Punga', '104','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Austinabad', '105','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bamboo Flat', '106','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Barren Island', '107','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Beadonabad', '108','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Betapur', '109','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bindraban', '110','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bonington', '111','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Brookesabad', '112','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Cadell Point', '113','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Calicut', '114','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chetamale', '115','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Cinque Islands', '116','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Defence Island', '117','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Digilpur', '118','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dolyganj', '119','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Flat Island', '120','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Geinyale', '121','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Great Coco Island', '122','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Haddo', '123','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Havelock Island', '124','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Henry Lawrence Island', '125','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Herbertabad', '126','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hobdaypur', '127','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ilichar', '128','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ingoie', '128','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Inteview Island', '130','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jangli Ghat', '131','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jhon Lawrence Island', '132','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karen', '133','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kartara', '134','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('KYD Islannd', '135','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Landfall Island', '136','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Little Andmand', '137','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Little Coco Island', '138','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Long Island', '138','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Maimyo', '140','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Malappuram', '141','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Manglutan', '142','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Manpur', '143','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mitha Khari', '144','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Neill Island', '145','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nicobar Island', '146','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('North Brother Island', '147','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('North Passage Island', '148','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('North Sentinel Island', '149','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nothen Reef Island', '150','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Outram Island', '151','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pahlagaon', '152','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Palalankwe', '153','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Passage Island', '154','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Phaiapong', '155','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Phoenix Island', '156','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Port Blair', '157','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Preparis Island', '158','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Protheroepur', '159','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rangachang', '160','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rongat', '161','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rutland Island', '162','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sabari', '163','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Saddle Peak', '164','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Shadipur', '165','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Smith Island', '166','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sound Island', '167','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('South Sentinel Island', '168','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Spike Island', '169','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tarmugli Island', '170','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Taylerabad', '171','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Titaije', '172','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Toibalawe', '173','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tusonabad', '174','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Island', '175','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Wimberleyganj', '176','1');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Yadita', '177','1');


-- Andhra Pradesh
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Adilabad', '201','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Anantapur', '201','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chittoor', '203','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Cuddapah', '204','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('East Godavari', '205','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Guntur', '206','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hyderabad', '207','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karimnagar', '208','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Khammam', '209','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Krishna', '210','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kurnool', '211','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mahabubnagar', '212','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Medak', '213','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nalgonda', '214','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nellore', '215','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nizamabad', '216','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Prakasam', '217','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rangareddy', '218','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Srikakulam', '219','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Visakhapatnam', '220','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Vizianagaram', '221','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Warangal', '222','23');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Godavari', '223','23');



-- Arunachal Pradesh

INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Anjaw', '301',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Changlang', '302',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dibang Valley', '303',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('East Kameng', '304',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('East Siang', '305',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Itanagar', '306',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kurung Kumey', '307',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lohit', '308',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lower Dibang Valley', '309',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lower Subansiri', '310',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Papum Pare', '311',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tawang', '312',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tirap', '313',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Upper Siang', '314',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Upper Subansiri', '315',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Kameng', '316',1);
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Siang', '317',1);

-- Assam
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Barpeta', '401','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bongaigaon', '402','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Cachar', '403','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Darrang', '404','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dhemaji', '405','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dhubri', '406','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dibrugarh', '407','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Goalpara', '408','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Golaghat', '409','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Guwahati', '410','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hailakandi', '411','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jorhat', '412','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kamrup', '413','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karbi Anglong', '414','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karimganj', '415','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kokrajhar', '416','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lakhimpur', '417','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Marigaon', '418','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nagaon', '419','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nalbari', '420','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('North Cachar Hills', '421','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Silchar', '422','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sivasagar', '423','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sonitpur', '424','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tinsukia', '425','11');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Udalguri', '426','11');


-- Bihar
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Araria', '501','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Aurangabad', '502','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Banka', '503','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Begusarai', '504','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhagalpur', '505','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhojpur', '506','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Buxar', '507','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Darbhanga', '508','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('East Champaran', '509','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gaya', '510','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gopalganj', '511','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jamshedpur', '512','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jamui', '513','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jehanabad', '514','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kaimur (Bhabua)', '515','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Katihar', '516','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Khagaria', '517','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kishanganj', '518','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lakhisarai', '519','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Madhepura', '520','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Madhubani', '521','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Munger', '522','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Muzaffarpur', '523','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nalanda', '524','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nawada', '525','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Patna', '526','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Purnia', '527','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rohtas', '528','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Saharsa', '529','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Samastipur', '530','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Saran', '531','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sheikhpura', '532','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sheohar', '533','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sitamarhi', '534','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Siwan', '535','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Supaul', '536','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Vaishali', '537','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Champaran', '538','5');



-- Chandigarh
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chandigarh', '601','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mani Marja', '602','16');


-- Chhattisgarh
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bastar', '701','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhilai', '702','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bijapur', '703','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bilaspur', '704','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dhamtari', '705','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Durg', '706','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Janjgir-Champa', '707','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jashpur', '708','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kabirdham-Kawardha', '709','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Korba', '710','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Korea', '711','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mahasamund', '712','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Narayanpur', '713','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Norh Bastar-Kanker', '714','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Raigarh', '715','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Raipur', '716','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rajnandgaon', '717','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('South Bastar-Dantewada', '718','3');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Surguja', '719','3');


-- Dadra & Nagar Haveli
INSERT INTO csp_app_cities (city_name,pk_city_code,fk_state_code_id) VALUES
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Amal', '801','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Amli', '802','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bedpa', '803','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chikhli', '804','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dadra & Nagar Haveli', '805','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dahikhed', '806','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dolara', '807','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Galonda', '808','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kanadi', '809','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karchond', '810','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Khadoli', '811','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kharadpada', '812','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kherabari', '813','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kherdi', '814','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kothar', '815','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Luari', '816','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mashat', '817','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rakholi', '818','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rudana', '819','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Saili', '820','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sili', '821','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Silvassa', '822','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sindavni', '823','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Udva', '824','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Umbarkoi', '825','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Vansda', '826','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Vasona', '827','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Velugam', '828','8');


-- Daman and Diu
INSERT INTO csp_app_cities (city_name,pk_city_code,fk_state_code_id) VALUES
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Brancavare', '901','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dagasi', '902','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Daman', '903','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Diu', '904','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Magarvara', '905','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nagwa', '906','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pariali', '907','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Passo Covo', '908','9');


-- Delhi
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Central Delhi', '1001','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('East Delhi', '1002','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('New Delhi', '1003','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('North Delhi', '1004','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('North East Delhi', '1005','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('North West Delhi', '1006','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Old Delhi', '1007','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('South Delhi', '1008','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('South West Delhi', '1009','18');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Delhi', '1010','18');

--  Goa
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Canacona', '1101','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Candolim', '1102','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chinchinim', '1103','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Cortalim', '1104','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Goa', '1105','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jua', '1106','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Madgaon', '1107','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mahem', '1108','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mapuca', '1109','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Marmagao', '1110','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Panji', '1111','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ponda', '1112','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sanvordem', '1113','29');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Terekhol', '1114','29');


-- Gujarat
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ahmedabad', '1201','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Amreli', '1202','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Anand', '1203','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Banaskantha', '1204','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Baroda', '1205','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bharuch', '1206','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhavnagar', '1207','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dahod', '1208','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dang', '1209','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dwarka', '1210','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gandhinagar', '1211','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jamnagar', '1212','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Junagadh', '1213','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kheda', '1214','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kutch', '1215','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mehsana', '1216','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nadiad', '1217','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Narmada', '1218','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Navsari', '1219','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Panchmahals', '1220','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Patan', '1221','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Porbandar', '1222','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rajkot', '1223','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sabarkantha', '1224','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Surat', '1225','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Surendranagar', '1226','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Vadodara', '1227','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Valsad', '1228','30');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Vapi', '1229','30');


-- Haryana
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ambala', '1301','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhiwani', '1302','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Faridabad', '1303','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Fatehabad', '1304','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gurgaon', '1305','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hisar', '1306','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jhajjar', '1307','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jind', '1308','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kaithal', '1309','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karnal', '1310','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kurukshetra', '1311','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mahendragarh', '1312','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mewat', '1313','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Panchkula', '1314','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Panipat', '1315','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rewari', '1316','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rohtak', '1317','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sirsa', '1318','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sonipat', '1319','15');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Yamunanagar', '1320','15');


-- Himachal Pradesh
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bilaspur', '1401','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chamba', '1402','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dalhousie', '1403','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hamirpur', '1404','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kangra', '1405','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kinnaur', '1406','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kullu', '1407','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lahaul & Spiti', '1408','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mandi', '1409','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Shimla', '1410','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sirmaur', '1411','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Solan', '1412','16');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Una', '1413','16');



-- Jammu & Kashmir
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Anantnag', '1501','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Baramulla', '1502','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Budgam', '1503','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Doda', '1504','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jammu', '1505','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kargil', '1506','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kathua', '1507','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kupwara', '1508','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Leh', '1509','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Poonch', '1510','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pulwama', '1511','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rajauri', '1512','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Srinagar', '1513','17');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Udhampur', '1514','17');



-- Jharkhand
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bokaro', '1601','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chatra', '1602','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Deoghar', '1603','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dhanbad', '1604','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dumka', '1605','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('East Singhbhum', '1606','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Garhwa', '1607','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Giridih', '1608','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Godda', '1609','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gumla', '1610','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hazaribag', '1611','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jamtara', '1612','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Koderma', '1613','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Latehar', '1614','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lohardaga', '1615','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pakur', '1616','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Palamu', '1617','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ranchi', '1618','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sahibganj', '1619','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Seraikela', '1620','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Simdega', '1621','4');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Singhbhum', '1622','4');


-- Karnataka
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bagalkot', '1701','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bangalore', '1702','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bangalore Rural', '1703','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Belgaum', '1704','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bellary', '1705','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhatkal', '1706','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bidar', '1707','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bijapur', '1708','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chamrajnagar', '1709','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chickmagalur', '1710','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chikballapur', '1711','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chitradurga', '1712','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dakshina Kannada', '1713','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Davanagere', '1714','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dharwad', '1715','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gadag', '1716','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gulbarga', '1717','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hampi', '1718','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hassan', '1719','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Haveri', '1720','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hospet', '1721','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karwar', '1722','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kodagu', '1723','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kolar', '1724','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Koppal', '1725','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Madikeri', '1726','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mandya', '1727','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mangalore', '1728','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Manipal', '1729','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mysore', '1730','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Raichur', '1731','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Shimoga', '1732','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sirsi', '1733','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sringeri', '1734','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Srirangapatna', '1735','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tumkur', '1736','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Udupi', '1737','24');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Uttara Kannada', '1738','24');


-- Kerala
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Alappuzha', '1801','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Alleppey', '1802','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Alwaye', '1803','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ernakulam', '1804','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Idukki', '1805','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kannur', '1806','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kasargod', '1807','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kochi', '1808','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kollam', '1809','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kottayam', '1810','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kovalam', '1811','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kozhikode', '1812','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Malappuram', '1813','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Palakkad', '1814','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pathanamthitta', '1815','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Perumbavoor', '1816','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Thiruvananthapuram', '1817','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Thrissur', '1818','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Trichur', '1819','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Trivandrum', '1820','25');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Wayanad', '1821','25');


-- Lakshadweep
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Agatti Island', '1901','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bingaram Island', '1902','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bitra Island', '1903','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chetlat Island', '1904','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kadmat Island', '1905','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kalpeni Island', '1906','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kavaratti Island', '1907','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kiltan Island', '1908','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lakshadweep Sea', '1909','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Minicoy Island', '1910','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('North Island', '1911','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('South Island', '1912','19');


-- Madhya Pradesh
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Anuppur', '2001','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ashoknagar', '2002','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Balaghat', '2003','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Barwani', '2004','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Betul', '2005','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhind', '2006','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhopal', '2007','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Burhanpur', '2008','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chhatarpur', '2009','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chhindwara', '2010','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Damoh', '2011','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Datia', '2012','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dewas', '2013','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dhar', '2014','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dindori', '2015','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Guna', '2016','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gwalior', '2017','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Harda', '2018','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hoshangabad', '2019','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Indore', '2020','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jabalpur', '2021','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jagdalpur', '2022','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jhabua', '2023','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Katni', '2024','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Khandwa', '2025','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Khargone', '2026','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mandla', '2027','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mandsaur', '2028','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Morena', '2029','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Narsinghpur', '2030','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Neemuch', '2031','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Panna', '2032','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Raisen', '2033','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rajgarh', '2034','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ratlam', '2035','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rewa', '2036','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sagar', '2037','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Satna', '2038','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sehore', '2039','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Seoni', '2040','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Shahdol', '2041','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Shajapur', '2042','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sheopur', '2043','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Shivpuri', '2044','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sidhi', '2045','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tikamgarh', '2046','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ujjain', '2047','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Umaria', '2048','32');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Vidisha', '2049','32');



-- Maharashtra
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ahmednagar', '2101','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Akola', '2102','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Amravati', '2103','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Aurangabad', '2104','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Beed', '2105','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhandara', '2106','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Buldhana', '2107','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chandrapur', '2108','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dhule', '2109','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gadchiroli', '2110','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gondia', '2111','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hingoli', '2112','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jalgaon', '2113','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jalna', '2114','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kolhapur', '2115','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Latur', '2116','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mahabaleshwar', '2117','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mumbai', '2118','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mumbai City', '2119','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mumbai Suburban', '2120','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nagpur', '2121','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nanded', '2122','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nandurbar', '2123','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nashik', '2124','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Osmanabad', '2125','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Parbhani', '2126','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pune', '2127','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Raigad', '2128','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ratnagiri', '2129','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sangli', '2130','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Satara', '2131','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sholapur', '2132','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sindhudurg', '2133','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Thane', '2134','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Wardha', '2135','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Washim', '2136','31');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Yavatmal', '2137','31');


-- Manipur
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bishnupur', '2201','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chandel', '2202','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Churachandpur', '2203','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Imphal East', '2204','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Imphal West', '2205','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Senapati', '2206','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tamenglong', '2207','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Thoubal', '2208','5');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ukhrul', '2209','5');



-- Meghalaya6
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('East Garo Hills', '2301','6');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('East Khasi Hills', '2302','6');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jaintia Hills', '2303','6');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ri Bhoi', '2304','6');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Shillong', '2305','6');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('South Garo Hills', '2306','6');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Garo Hills', '2307','6');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('West Khasi Hills', '2308','6');



-- Mizoram7
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Aizawl', '2401','7');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Champhai', '2402','7');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kolasib', '2403','7');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lawngtlai', '2404','7');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lunglei', '2405','7');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mamit', '2406','7');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Saiha', '2407','7');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Serchhip', '2408','7');


-- Nagaland8
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dimapur', '2501','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kohima', '2502','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mokokchung', '2503','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mon', '2504','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Phek', '2505','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tuensang', '2506','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Wokha', '2507','8');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Zunheboto', '2508','8');



-- Orissa9
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Angul', '2601','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Balangir', '2602','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Balasore', '2603','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Baleswar', '2604','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bargarh', '2605','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Berhampur', '2606','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhadrak', '2607','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhubaneswar', '2608','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Boudh', '2609','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Cuttack', '2610','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Deogarh', '2611','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dhenkanal', '2612','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gajapati', '2613','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ganjam', '2614','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jagatsinghapur', '2615','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jajpur', '2616','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jharsuguda', '2617','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kalahandi', '2618','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kandhamal', '2619','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kendrapara', '2620','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kendujhar', '2621','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Khordha', '2622','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Koraput', '2623','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Malkangiri', '2624','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mayurbhanj', '2625','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nabarangapur', '2626','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nayagarh', '2627','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nuapada', '2628','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Puri', '2629','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rayagada', '2630','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rourkela', '2631','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sambalpur', '2632','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Subarnapur', '2633','9');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sundergarh', '2634','9');


-- Pondicherry26
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bahur', '2701','26');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karaikal', '2701','26');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mahe', '2701','26');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pondicherry', '2701','26');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Purnankuppam', '2701','26');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Valudavur', '2701','26');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Villianur', '2701','26');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Yanam', '2701','26');



-- Punjab19
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Amritsar', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Barnala', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bathinda', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Faridkot', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Fatehgarh Sahib', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ferozepur', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gurdaspur', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hoshiarpur', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jalandhar', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kapurthala', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ludhiana', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mansa', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Moga', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Muktsar', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nawanshahr', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pathankot', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Patiala', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rupnagar', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sangrur', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('SAS Nagar', '2801','19');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tarn Taran', '2801','19');




-- Rajasthan20
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ajmer', '2901','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Alwar', '2902','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Banswara', '2903','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Baran', '2904','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Barmer', '2905','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bharatpur', '2906','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhilwara', '2907','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bikaner', '2908','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bundi', '2909','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chittorgarh', '2910','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Churu', '2911','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dausa', '2912','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dholpur', '2913','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dungarpur', '2914','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hanumangarh', '2915','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jaipur', '2916','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jaisalmer', '2917','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jalore', '2918','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jhalawar', '2919','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jhunjhunu', '2920','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Jodhpur', '2921','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karauli', '2922','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kota', '2923','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nagaur', '2924','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pali', '2925','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pilani', '2926','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rajsamand', '2927','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sawai Madhopur', '2928','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sikar', '2929','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sirohi', '2930','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sri Ganganagar', '2931','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tonk', '2932','20');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Udaipur', '2933','20');


-- Sikkim10
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Barmiak', '3001','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Be', '3002','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bhurtuk', '3003','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chhubakha', '3004','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chidam', '3005','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chubha', '3006','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chumikteng', '3007','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dentam', '3008','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dikchu', '3009','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dzongri', '3010','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gangtok', '3011','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gauzing', '3012','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Gyalshing', '3013','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hema', '3014','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kerung', '3015','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lachen', '3016','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lachung', '3017','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lema', '3018','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lingtam', '3019','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Lungthu', '3020','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mangan', '3021','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Namchi', '3022','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Namthang', '3023','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nanga', '3024','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nantang', '3025','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Naya Bazar', '3026','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Padamachen', '3027','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pakhyong', '3028','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pemayangtse', '3029','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Phensang', '3030','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rangli', '3031','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rinchingpong', '3032','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sakyong', '3033','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Samdong', '3034','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Singtam', '3035','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Siniolchu', '3035','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sombari', '3036','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Soreng', '3037','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sosing', '3038','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tekhug', '3039','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Temi', '3040','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tsetang', '3041','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tsomgo', '3042','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tumlong', '3043','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Yangang', '3044','10');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Yumtang', '3045','10');



-- Tamil Nadu27
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chennai', '3101','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chidambaram', '3102','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Chingleput', '3103','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Coimbatore', '3104','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Courtallam', '3105','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Cuddalore', '3106','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dharmapuri', '3107','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dindigul', '3108','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Erode', '3109','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Hosur', '3110','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kanchipuram', '3111','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kanyakumari', '3112','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karaikudi', '3113','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Karur', '3114','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kodaikanal', '3115','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kovilpatti', '3116','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Krishnagiri', '3117','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kumbakonam', '3118','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Madurai', '3119','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Mayiladuthurai', '3120','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nagapattinam', '3121','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nagarcoil', '3122','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Namakkal', '3123','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Neyveli', '3124','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Nilgiris', '3125','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ooty', '3126','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Palani', '3127','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Perambalur', '3128','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pollachi', '3129','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Pudukkottai', '3130','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Rajapalayam', '3131','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ramanathapuram', '3132','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Salem', '3133','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sivaganga', '3134','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Sivakasi', '3135','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Thanjavur', '3136','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Theni', '3137','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Thoothukudi', '3138','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tiruchirappalli', '3139','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tirunelveli', '3140','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tirupur', '3141','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tiruvallur', '3142','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tiruvannamalai', '3143','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tiruvarur', '3144','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Trichy', '3145','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tuticorin', '3146','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Vellore', '3147','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Villupuram', '3148','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Virudhunagar', '3149','27');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Yercaud', '3150','27');



-- Tripura12
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Agartala', '3201','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Ambasa', '3202','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Bampurbari', '3203','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Belonia', '3204','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dhalai', '3205','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Dharam Nagar', '3206','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kailashahar', '3207','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Kamal Krishnabari', '3208','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Khopaiyapara', '3209','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Khowai', '3210','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Phuldungsei', '3211','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Radha Kishore Pur', '3212','12');
INSERT INTO CSP_APP_CITIES (CITY_NAME,PK_CITY_CODE,FK_STATE_CODE_ID) VALUES('Tripura', '3213','12');







insert into "csp_app_master_candidate_fields" values ( 1,'fk_location_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 2,'Salary_Type_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 3,'Sub_Source_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 4,'Type_of_Hiring_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 5,'candidate_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 6,'documentation_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 7,'email_creation_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 8,'fk_city_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 9,'fk_department_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 10,'fk_designation_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 11,'fk_entity_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 12,'fk_function_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 13,'fk_region_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 14,'fk_state_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 15,'fk_subteam_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 16,'fk_team_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 17,'fk_vendor_code_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 18,'it_intimation_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 19,'joining_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 20,'laptop_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 21,'loi_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 22,'offer_letter_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 23,'onboarding_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 24,'status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 25,'vendor_status_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 26,'Date_of_Joining','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 27,'Gross_Salary_Entered','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 28,'Gross_Salary_Amount','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 29,'created_date_time','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 30,'modified_date_time','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 31,'delay_date','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 32,'Gender_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 33,'Laptop_Allocation_id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 34,'First_Name','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 35,'Middle_Name','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 36,'Last_Name','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 37,'Date_of_Birth','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 38,'Contact_Number','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 39,'Emergency_Contact_Number','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 40,'Personal_Email_Id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 41,'Father_Name','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 42,'Mother_Name','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 43,'Aadhaar_Number','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 44,'PAN_Number','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 45,'modified_by','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 46,'Replacement','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 47,'Referral','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 48,'physically_challenged','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 49,'TA_Spoc_Email_Id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 50,'Onboarding_Spoc_Email_Id','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 51,'Reporting_Manager','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 52,'Reporting_Manager_E_Mail_ID','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 53,'E_Mail_ID_Creation','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 54,'pk_candidate_code','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 55,'ecode_status','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 56,'created_by','sdf',null,1);
insert into "csp_app_master_candidate_fields" values ( 57,'remarks','sdf',null,1);
