# Generated by Django 3.1.1 on 2020-09-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master_agency',
            fields=[
                ('pk_agency_code', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='master_city',
            fields=[
                ('pk_city_code', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='master_department',
            fields=[
                ('pk_department_code', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('fk_agency_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_agency')),
            ],
        ),
        migrations.CreateModel(
            name='master_designation',
            fields=[
                ('pk_designation_code', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='master_entity',
            fields=[
                ('pk_entity_code', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='master_function',
            fields=[
                ('pk_function_code', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('fk_department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_department')),
            ],
        ),
        migrations.CreateModel(
            name='master_region',
            fields=[
                ('pk_region_code', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('fk_designation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_designation')),
            ],
        ),
        migrations.CreateModel(
            name='master_team',
            fields=[
                ('pk_team_code', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('fk_function_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_function')),
            ],
        ),
        migrations.CreateModel(
            name='master_sub_team',
            fields=[
                ('pk_sub_team_code', models.AutoField(primary_key=True, serialize=False)),
                ('sub_team_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('fk_team_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_team')),
            ],
        ),
        migrations.CreateModel(
            name='master_state',
            fields=[
                ('pk_state_code', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('fk_region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_region')),
            ],
        ),
        migrations.CreateModel(
            name='master_location',
            fields=[
                ('pk_location_code', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('fk_city_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_city')),
            ],
        ),
        migrations.AddField(
            model_name='master_designation',
            name='fk_sub_team_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_sub_team'),
        ),
        migrations.AddField(
            model_name='master_city',
            name='fk_region_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_region'),
        ),
        migrations.AddField(
            model_name='master_agency',
            name='fk_entity_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_entity'),
        ),
    ]
