# Generated by Django 3.1.1 on 2020-09-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_agency',
            name='agency_email_id',
            field=models.EmailField(default='sdf@sdf.com', max_length=254),
        ),
        migrations.AddField(
            model_name='master_agency',
            name='agency_email_id_password',
            field=models.CharField(default='no', max_length=100),
        ),
        migrations.AddField(
            model_name='master_agency',
            name='agency_phone_number',
            field=models.CharField(default=2, max_length=10),
        ),
        migrations.AddField(
            model_name='master_agency',
            name='spoc_name',
            field=models.CharField(default='d', max_length=50),
        ),
    ]
