# Generated by Django 3.1.1 on 2020-11-06 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0002_gross_salary_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('city_name', models.CharField(max_length=100)),
                ('pk_city_code', models.AutoField(primary_key=True, serialize=False)),
                ('fk_state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_state')),
            ],
        ),
    ]
