# Generated by Django 3.1.1 on 2020-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0003_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='pk_city_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
