# Generated by Django 3.1.1 on 2020-09-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0003_auto_20200907_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_department',
            name='fk_entity_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_entity'),
        ),
    ]
