# Generated by Django 3.1.1 on 2020-11-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0004_auto_20201106_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='fk_state_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.states'),
        ),
    ]
