# Generated by Django 3.1.1 on 2020-09-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0004_auto_20200907_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='gender',
            fields=[
                ('pk_gender_code', models.AutoField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hiring_type',
            fields=[
                ('pk_hiring_type_code', models.AutoField(primary_key=True, serialize=False)),
                ('hiring_type_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='laptop_allocation',
            fields=[
                ('pk_laptop_allocation_code', models.AutoField(primary_key=True, serialize=False)),
                ('option_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('pk_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=10)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_source',
            fields=[
                ('pk_sub_source_code', models.AutoField(primary_key=True, serialize=False)),
                ('sub_source_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='salary_type',
            fields=[
                ('pk_salary_type_code', models.AutoField(primary_key=True, serialize=False)),
                ('salary_type_name', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='master_candidate',
            fields=[
                ('pk_candidate_code', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Joining', models.DateField()),
                ('Father_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.DateField()),
                ('Aadhaar_Number', models.CharField(max_length=12)),
                ('PAN_Number', models.CharField(max_length=10)),
                ('Contact_Number', models.CharField(max_length=10)),
                ('Emergency_Contact_Number', models.CharField(max_length=10)),
                ('If_Replacement', models.CharField(max_length=20)),
                ('If_Referral', models.CharField(max_length=20)),
                ('Reporting_Manager', models.CharField(max_length=20)),
                ('Reporting_Manager_E_Mail_ID', models.CharField(max_length=100)),
                ('E_Mail_ID_Creation', models.CharField(max_length=10)),
                ('Gross_Salary_Amount', models.FloatField()),
                ('Agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_agency')),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_city')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_department')),
                ('Designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_designation')),
                ('Entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_entity')),
                ('Function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_function')),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.gender')),
                ('Laptop_Allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.laptop_allocation')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_location')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_region')),
                ('Salary_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.salary_type')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_state')),
                ('Sub_Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.sub_source')),
                ('Sub_Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_sub_team')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_team')),
                ('Type_of_Hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.hiring_type')),
            ],
        ),
        migrations.AddField(
            model_name='laptop_allocation',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AddField(
            model_name='hiring_type',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AddField(
            model_name='gender',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_agency',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_city',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_department',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_designation',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_entity',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_function',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_location',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_region',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_state',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_sub_team',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
        migrations.AlterField(
            model_name='master_team',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
    ]
