# Generated by Django 3.1.1 on 2020-11-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0005_auto_20201106_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy_candidate',
            name='physically_challenged',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='physically_challenged',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.CreateModel(
            name='reject_reason',
            fields=[
                ('pk_reason_code', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=300)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(blank=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('fk_candidate_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_candidate')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
            ],
        ),
    ]
