# Generated by Django 3.1.1 on 2020-09-09 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0005_auto_20200908_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_city',
            name='fk_region_code',
        ),
        migrations.AddField(
            model_name='master_city',
            name='fk_state_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_state'),
        ),
    ]
