# Generated by Django 3.1.1 on 2020-09-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0006_auto_20200909_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_city',
            name='fk_state_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_state'),
        ),
    ]
