# Generated by Django 3.1.1 on 2020-11-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0006_auto_20201107_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy_candidate',
            name='fk_vendor_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_vendor'),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='fk_vendor_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_vendor'),
        ),
    ]
