# Generated by Django 3.1.1 on 2020-11-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0007_auto_20201118_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='gross_salary_history',
            name='created_date_time',
            field=models.DateTimeField(blank=True, default='2020-11-17 20:15:51.066903+05:30', null=True),
        ),
    ]
