# Generated by Django 3.1.1 on 2020-09-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0007_auto_20200909_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_candidate',
            old_name='If_Referral',
            new_name='Referral',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='If_Replacement',
            new_name='Replacement',
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='created_by',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='created_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='modified_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
    ]
