# Generated by Django 3.1.1 on 2020-11-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0008_gross_salary_history_created_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gross_salary_history',
            name='created_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
