# Generated by Django 3.1.1 on 2020-09-10 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0009_auto_20200909_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_candidate',
            name='Father_Date_of_Birth',
            field=models.DateField(default=datetime.date(2020, 9, 10)),
        ),
    ]
