# Generated by Django 3.1.1 on 2020-09-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0010_master_candidate_father_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_salary',
            fields=[
                ('pk_salary_code', models.AutoField(primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='candidate_status',
            fields=[
                ('pk_status_code', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='master_vendor',
            fields=[
                ('pk_vendor_code', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('spoc_name', models.CharField(max_length=50)),
                ('spoc_email_id', models.EmailField(max_length=254)),
                ('vendor_phone_number', models.CharField(max_length=10)),
                ('vendor_email_id', models.EmailField(max_length=254)),
                ('vendor_email_id_password', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('fk_entity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_entity')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
            ],
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='City',
            new_name='fk_city_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='Department',
            new_name='fk_department_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='Designation',
            new_name='fk_designation_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='Entity',
            new_name='fk_entity_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='Function',
            new_name='fk_function_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='Location',
            new_name='fk_location_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='Region',
            new_name='fk_region_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='State',
            new_name='fk_state_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='Sub_Team',
            new_name='fk_subteam_code',
        ),
        migrations.RenameField(
            model_name='master_candidate',
            old_name='Team',
            new_name='fk_team_code',
        ),
        migrations.RemoveField(
            model_name='master_candidate',
            name='Agency',
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='Father_Date_of_Birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='pk_candidate_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='master_agency',
        ),
        migrations.AddField(
            model_name='candidate_salary',
            name='candidate_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_candidate'),
        ),
        migrations.AddField(
            model_name='candidate_salary',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status'),
        ),
    ]
