# Generated by Django 3.1.1 on 2020-11-22 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0010_candidate_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_candidate_fields',
            fields=[
                ('pk_field_code', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
            ],
        ),
    ]
