# Generated by Django 3.1.1 on 2020-09-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0011_auto_20200911_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_candidate',
            name='candidate_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.candidate_status'),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='fk_vendor_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_vendor'),
        ),
    ]
