# Generated by Django 3.1.1 on 2020-09-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0012_auto_20200911_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_candidate',
            name='fk_vendor_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_vendor'),
        ),
    ]
