# Generated by Django 3.0.4 on 2020-09-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0013_auto_20200911_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_region',
            name='fk_designation_code',
        ),
        migrations.AddField(
            model_name='master_region',
            name='fk_dentity_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_entity'),
        ),
    ]
