# Generated by Django 3.1.1 on 2020-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0013_auto_20201214_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_history',
            name='new_value',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='candidate_history',
            name='old_value',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
