# Generated by Django 3.1.1 on 2020-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0014_auto_20200912_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_candidate',
            name='Personal_Email_Id',
            field=models.EmailField(default='sdfworkk@gmail.com', max_length=254),
        ),
    ]
