# Generated by Django 3.1.1 on 2020-12-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0014_auto_20201215_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_document',
            name='submit_status',
            field=models.IntegerField(default=0),
        ),
    ]
