# Generated by Django 3.1.1 on 2020-12-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0015_candidate_document_submit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_document',
            name='submit_status',
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='submit_status',
            field=models.IntegerField(default=0),
        ),
    ]
