# Generated by Django 3.1.1 on 2020-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0015_master_candidate_personal_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_candidate',
            name='Personal_Email_Id',
            field=models.EmailField(max_length=254),
        ),
    ]
