# Generated by Django 3.1.1 on 2020-09-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0016_auto_20200912_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_region',
            old_name='fk_dentity_code',
            new_name='fk_entity_code',
        ),
    ]
