# Generated by Django 3.1.1 on 2020-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0017_auto_20200914_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_location',
            name='location_code',
            field=models.CharField(default='d3126', max_length=10),
        ),
    ]
