# Generated by Django 3.1.1 on 2020-09-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0018_master_location_location_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_location',
            name='location_code',
            field=models.CharField(max_length=10),
        ),
    ]
