# Generated by Django 3.1.1 on 2020-09-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0019_auto_20200914_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_document',
            fields=[
                ('pk_document_code', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('file_upload', models.FileField(upload_to='')),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('fk_candidate_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_candidate')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
            ],
        ),
    ]
