# Generated by Django 3.1.1 on 2020-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0020_candidate_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_candidate',
            name='Onboarding_Spoc_Email_Id',
            field=models.EmailField(default='dummy@dummy.com', max_length=254),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='TA_Spoc_Email_Id',
            field=models.EmailField(default='dummy@dummy.com', max_length=254),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='location_code',
            field=models.CharField(default='h76', max_length=10),
        ),
    ]
