# Generated by Django 3.1.1 on 2020-09-16 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0022_auto_20200916_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_candidate_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_candidate')),
            ],
        ),
    ]
