# Generated by Django 3.1.1 on 2020-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0023_candidate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_code',
            name='pk_candidate_code',
            field=models.CharField(max_length=10),
        ),
    ]
