# Generated by Django 3.1.1 on 2020-09-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0025_onboarding_status_vendor_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vendor_status',
        ),
    ]
