# Generated by Django 3.1.1 on 2020-09-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0027_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_candidate',
            name='onboarding_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='csp_app.onboarding_status'),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='vendor_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='csp_app.vendor_status'),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='candidate_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='csp_app.candidate_status'),
        ),
    ]
