# Generated by Django 3.1.1 on 2020-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0028_auto_20200916_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_candidate',
            name='Personal_Email_Id',
            field=models.CharField(default='sadaf.shaikh@udaan.com', max_length=100),
        ),
    ]
