# Generated by Django 3.1.1 on 2020-09-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0030_auto_20200916_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='candidate_code',
        ),
    ]
