# Generated by Django 3.1.1 on 2020-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0031_delete_candidate_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='csp_candidate_code',
            fields=[
                ('pk_count', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_code', models.CharField(default='C000000004', max_length=10)),
            ],
        ),
    ]
