# Generated by Django 3.1.1 on 2020-09-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0032_csp_candidate_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='mandatory_documents',
            fields=[
                ('pk_mandatory_code', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=50)),
            ],
        ),
    ]
