# Generated by Django 3.1.1 on 2020-09-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0033_mandatory_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_document',
            name='document_catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.mandatory_documents'),
        ),
    ]
