# Generated by Django 3.1.1 on 2020-09-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0035_auto_20200920_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_location',
            name='location_code',
            field=models.CharField(max_length=20),
        ),
    ]
