# Generated by Django 3.1.1 on 2020-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0036_auto_20200925_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill_type',
            fields=[
                ('pk_skill_code', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=20)),
            ],
        ),
    ]
