# Generated by Django 3.1.1 on 2020-09-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0037_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_designation',
            name='fk_skill_code',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='csp_app.skill_type'),
        ),
    ]
