# Generated by Django 3.1.1 on 2020-09-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0038_master_designation_fk_skill_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_designation',
            name='fk_skill_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.skill_type'),
        ),
    ]
