# Generated by Django 3.1.1 on 2020-09-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0039_auto_20200925_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_minimum_wages',
            fields=[
                ('pk_minimum_wages_code', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('zone_name', models.CharField(max_length=10)),
                ('skill_name', models.CharField(max_length=20)),
                ('wages', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='states',
            fields=[
                ('pk_state_code', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='zones',
            fields=[
                ('pk_zone_code', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=50)),
            ],
        ),
    ]
