# Generated by Django 3.1.1 on 2020-09-26 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0040_master_minimum_wages_states_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_minimum_wages',
            name='skill_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.skill_type'),
        ),
        migrations.AlterField(
            model_name='master_minimum_wages',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.states'),
        ),
        migrations.AlterField(
            model_name='master_minimum_wages',
            name='zone_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.zones'),
        ),
    ]
