# Generated by Django 3.1.1 on 2020-09-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0041_auto_20200926_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_minimum_wages',
            old_name='skill_name',
            new_name='fk_skill_code',
        ),
        migrations.RenameField(
            model_name='master_minimum_wages',
            old_name='state_name',
            new_name='fk_state_code',
        ),
        migrations.RenameField(
            model_name='master_minimum_wages',
            old_name='zone_name',
            new_name='fk_zone_code',
        ),
    ]
