# Generated by Django 3.1.1 on 2020-09-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0042_auto_20200926_1019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='master_minimum_wages',
        ),
    ]
