# Generated by Django 3.1.1 on 2020-09-26 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0043_delete_master_minimum_wages'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_minimum_wages',
            fields=[
                ('pk_minimum_wages_code', models.AutoField(primary_key=True, serialize=False)),
                ('wages', models.FloatField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('fk_skill_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.skill_type')),
                ('fk_state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.states')),
                ('fk_zone_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.zones')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
            ],
        ),
    ]
