# Generated by Django 3.1.1 on 2020-09-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0046_auto_20200926_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_candidate',
            name='Referral',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='Replacement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
