# Generated by Django 3.1.1 on 2020-09-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0047_auto_20200926_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='port_list',
            fields=[
                ('pk_port_code', models.AutoField(primary_key=True, serialize=False)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='smtp_list',
            fields=[
                ('pk_smtp_code', models.AutoField(primary_key=True, serialize=False)),
                ('smtp', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='csp_candidate_code',
            name='candidate_code',
            field=models.CharField(max_length=10),
        ),
    ]
