# Generated by Django 3.1.1 on 2020-09-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0049_auto_20200926_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_vendor',
            name='vendor_email_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.port_list'),
        ),
        migrations.AlterField(
            model_name='master_vendor',
            name='vendor_smtp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='port_list',
            name='ssl',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='port_list',
            name='tls',
            field=models.BooleanField(),
        ),
    ]
