# Generated by Django 3.1.1 on 2020-09-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0051_auto_20200928_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary_structure_particulars',
            fields=[
                ('pk_ssp_code', models.AutoField(primary_key=True, serialize=False)),
                ('particulars', models.CharField(max_length=100)),
            ],
        ),
    ]
