# Generated by Django 3.1.1 on 2020-09-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0052_salary_structure_particulars'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_contributions_particulars',
            fields=[
                ('pk_ecp_code', models.AutoField(primary_key=True, serialize=False)),
                ('particulars', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employer_contributions_particulars',
            fields=[
                ('pk_ercp_code', models.AutoField(primary_key=True, serialize=False)),
                ('particulars', models.CharField(max_length=100)),
            ],
        ),
    ]
