# Generated by Django 3.1.1 on 2020-09-29 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0053_employee_contributions_particulars_employer_contributions_particulars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='master_entity',
            options={'get_latest_by': 'created_date_time'},
        ),
    ]
