# Generated by Django 3.1.1 on 2020-09-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0054_auto_20200929_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummy_candidate',
            fields=[
                ('pk_candidate_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Middle_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Date_of_Birth', models.CharField(max_length=20)),
                ('Contact_Number', models.CharField(max_length=10)),
                ('Emergency_Contact_Number', models.CharField(max_length=10)),
                ('Personal_Email_Id', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Father_Date_of_Birth', models.CharField(max_length=20)),
                ('Aadhaar_Number', models.CharField(max_length=12)),
                ('PAN_Number', models.CharField(max_length=10)),
                ('Date_of_Joining', models.CharField(max_length=20)),
                ('Replacement', models.CharField(blank=True, max_length=20, null=True)),
                ('Referral', models.CharField(blank=True, max_length=20, null=True)),
                ('location_code', models.CharField(max_length=10)),
                ('TA_Spoc_Email_Id', models.EmailField(max_length=254)),
                ('Onboarding_Spoc_Email_Id', models.EmailField(max_length=254)),
                ('Reporting_Manager', models.CharField(max_length=20)),
                ('Reporting_Manager_E_Mail_ID', models.CharField(max_length=100)),
                ('E_Mail_ID_Creation', models.CharField(max_length=10)),
                ('Gross_Salary_Amount', models.FloatField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_date_time', models.DateTimeField(blank=True, null=True)),
                ('Gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.gender')),
                ('Laptop_Allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.laptop_allocation')),
                ('Salary_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.salary_type')),
                ('Sub_Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.sub_source')),
                ('Type_of_Hiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.hiring_type')),
                ('candidate_status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='csp_app.candidate_status')),
                ('fk_city_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_city')),
                ('fk_department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_department')),
                ('fk_designation_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_designation')),
                ('fk_entity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_entity')),
                ('fk_function_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_function')),
                ('fk_location_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_location')),
                ('fk_region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_region')),
                ('fk_state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_state')),
                ('fk_subteam_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_sub_team')),
                ('fk_team_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_team')),
                ('fk_vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_vendor')),
                ('onboarding_status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='csp_app.onboarding_status')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.status')),
                ('vendor_status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='csp_app.vendor_status')),
            ],
        ),
    ]
