# Generated by Django 3.1.1 on 2020-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0055_dummy_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='dummy_candidate_code',
            fields=[
                ('pk_count', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_code', models.CharField(max_length=10)),
            ],
        ),
    ]
