# Generated by Django 3.1.1 on 2020-09-30 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0057_auto_20200930_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_region',
            name='region_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.zones'),
        ),
        migrations.AlterField(
            model_name='master_state',
            name='state_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='csp_app.states'),
        ),
    ]
