# Generated by Django 3.1.1 on 2020-10-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0059_auto_20201001_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary_structure',
            fields=[
                ('pk_salary_structure_code', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_code', models.CharField(max_length=10)),
                ('basic', models.FloatField()),
                ('house_rent_allowance', models.FloatField()),
                ('statutory_bonus', models.FloatField()),
                ('special_allowance', models.FloatField()),
                ('gross_salary', models.FloatField()),
                ('employee_pf', models.FloatField()),
                ('employee_esic', models.FloatField()),
                ('employee_total_contribution', models.FloatField()),
                ('employer_pf', models.FloatField()),
                ('employer_pf_admin', models.FloatField()),
                ('employer_esic', models.FloatField()),
                ('group_personal_accident', models.FloatField()),
                ('group_mediclaim_insurance', models.FloatField()),
                ('employer_total_contribution', models.FloatField()),
                ('cost_to_company', models.FloatField()),
            ],
        ),
    ]
