# Generated by Django 3.1.1 on 2020-10-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0060_salary_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_structure',
            name='annual_basic',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_cost_to_company',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_employee_esic',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_employee_pf',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_employee_total_contribution',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_employer_esic',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_employer_pf',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_employer_pf_admin',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_employer_total_contribution',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_gross_salary',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_group_mediclaim_insurance',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_group_personal_accident',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_house_rent_allowance',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_special_allowance',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_statutory_bonus',
            field=models.FloatField(default=1),
        ),
    ]
