# Generated by Django 3.1.1 on 2020-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0062_auto_20201002_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary_structure',
            name='annual_take_home_salary',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='annual_var',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='take_home_salary',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='salary_structure',
            name='variable',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='states',
            name='zone',
            field=models.CharField(default='east', max_length=10),
        ),
    ]
