# Generated by Django 3.1.1 on 2020-10-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0063_auto_20201005_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_structure',
            name='annual_take_home_salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary_structure',
            name='annual_var',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary_structure',
            name='take_home_salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary_structure',
            name='variable',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='states',
            name='zone',
            field=models.CharField(max_length=20),
        ),
    ]
