# Generated by Django 3.1.1 on 2020-10-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0064_auto_20201005_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_region',
            name='fk_entity_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.master_entity'),
        ),
        migrations.AlterField(
            model_name='master_region',
            name='region_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.zones'),
        ),
    ]
