# Generated by Django 3.1.1 on 2020-10-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0065_auto_20201006_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_candidate',
            name='location_code',
            field=models.CharField(max_length=100),
        ),
    ]
