# Generated by Django 3.1.1 on 2020-10-07 13:59

import csp_app.extvalidate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0066_auto_20201006_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate_document',
            name='file_upload',
            field=models.FileField(upload_to='documents/', validators=[csp_app.extvalidate.validate_file_extension]),
        ),
    ]
