# Generated by Django 3.1.1 on 2020-10-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0068_auto_20201012_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary_structure',
            name='annual_fixed_salary',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salary_structure',
            name='fixed_salary',
            field=models.FloatField(),
        ),
    ]
