# Generated by Django 3.1.1 on 2020-10-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0069_auto_20201012_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy_candidate',
            name='location_code',
            field=models.CharField(max_length=20),
        ),
    ]
