# Generated by Django 3.1.1 on 2020-10-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0070_auto_20201014_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummy_candidate',
            name='Father_Date_of_Birth',
        ),
        migrations.RemoveField(
            model_name='master_candidate',
            name='Father_Date_of_Birth',
        ),
        migrations.AddField(
            model_name='dummy_candidate',
            name='Mother_Name',
            field=models.CharField(default='Dharti Ma', max_length=100),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='Mother_Name',
            field=models.CharField(default='Dharti Ma', max_length=100),
        ),
    ]
