# Generated by Django 3.1.1 on 2020-10-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0071_auto_20201015_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy_candidate',
            name='Mother_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='Mother_Name',
            field=models.CharField(max_length=100),
        ),
    ]
