# Generated by Django 3.1.1 on 2020-10-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0072_auto_20201015_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy_candidate',
            name='location_code',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='location_code',
            field=models.FloatField(),
        ),
    ]
