# Generated by Django 3.1.1 on 2020-10-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0074_auto_20201019_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummy_candidate',
            name='Gross_Salary_Entered',
        ),
    ]
