# Generated by Django 3.1.1 on 2020-10-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0075_remove_dummy_candidate_gross_salary_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy_candidate',
            name='Gross_Salary_Entered',
            field=models.FloatField(default=0),
        ),
    ]
