# Generated by Django 3.1.1 on 2020-10-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0077_auto_20201021_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_candidate',
            name='documentation_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='csp_app.documentation_status'),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='ecode_status',
            field=models.CharField(default='Not Generated', max_length=50),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='email_creation_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='csp_app.email_creation_request_status'),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='it_intimation_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='csp_app.it_intimation_status'),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='joining_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='csp_app.joining_status'),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='laptop_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='csp_app.laptop_request_status'),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='loi_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='csp_app.loi_status'),
        ),
        migrations.AddField(
            model_name='master_candidate',
            name='offer_letter_status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='csp_app.offer_letter_status'),
        ),
    ]
