# Generated by Django 3.1.1 on 2020-10-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0078_auto_20201021_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_candidate',
            name='documentation_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='csp_app.documentation_status'),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='ecode_status',
            field=models.CharField(default='Not Applicable', max_length=50),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='it_intimation_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='csp_app.it_intimation_status'),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='joining_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='csp_app.joining_status'),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='offer_letter_status',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='csp_app.offer_letter_status'),
        ),
    ]
