# Generated by Django 3.1.1 on 2020-10-21 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0079_auto_20201021_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_candidate',
            name='email_creation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.email_creation_request_status'),
        ),
        migrations.AlterField(
            model_name='master_candidate',
            name='laptop_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csp_app.laptop_request_status'),
        ),
    ]
