# Generated by Django 3.1.1 on 2020-10-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0082_it_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_email_id',
            name='created_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='it_email_id',
            name='email_id',
            field=models.EmailField(max_length=100),
        ),
    ]
