# Generated by Django 3.1.1 on 2020-10-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0083_auto_20201023_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_candidate',
            name='delay_date',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
