# Generated by Django 3.1.1 on 2020-10-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0084_master_candidate_delay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_candidate',
            name='Date_of_Joining',
            field=models.DateField(),
        ),
    ]
