# Generated by Django 3.1.1 on 2020-10-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0085_auto_20201024_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy_candidate',
            name='Date_of_Joining',
            field=models.DateField(max_length=20),
        ),
    ]
