# Generated by Django 3.1.1 on 2020-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0086_auto_20201024_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_candidate',
            name='remarks',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
