# Generated by Django 3.1.1 on 2020-10-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0087_master_candidate_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_vendor',
            name='group_id',
            field=models.IntegerField(default=1),
        ),
    ]
