# Generated by Django 3.1.1 on 2020-10-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp_app', '0089_auto_20201031_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_ids',
            name='id',
        ),
        migrations.AlterField(
            model_name='group_ids',
            name='group_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
